// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'ENTER_FIREBASE_API_KEY',
    appId: '1:29403172094:web:7b5f4e00e48a1b2a6aa9af',
    messagingSenderId: '29403172094',
    projectId: 'commuteconnect-791a5 ',
    authDomain: 'commuteconnect-791a5 .firebaseapp.com',
    databaseURL: 'https://commuteconnect-791a5 -default-rtdb.firebaseio.com',
    storageBucket: 'commuteconnect-791a5 .appspot.com',
    measurementId: 'G-Y86M6CNXPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'ENTER_FIREBASE_API_KEY',
    appId: '1:379792293272:android:d41240ce4021b54094bfed',
    messagingSenderId: '379792293272',
    projectId: 'commuteconnect-791a5',
    databaseURL: 'https://commuteconnect-791a5-default-rtdb.firebaseio.com/',
    storageBucket: 'commuteconnect-791a5.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyCjrd2UgBE96b5VLzMDll4O2Ke4tvCZTy8',
  //   appId: '1:29403172094:ios:6ac2194fbcc42edd6aa9af',
  //   messagingSenderId: '29403172094',
  //   projectId: 'commuteconnect-791a5',
  //   databaseURL: 'https://commuteconnect-791a5-default-rtdb.firebaseio.com',
  //   storageBucket: 'commuteconnect-791a5.appspot.com',
  //   iosClientId: '29403172094-ailnalfvg49ftr38rgahv6pjp4p2d8a2.apps.googleusercontent.com',
  //   iosBundleId: 'com.egoncastle.users',
  // );
  //
  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyCjrd2UgBE96b5VLzMDll4O2Ke4tvCZTy8',
  //   appId: '1:29403172094:ios:6ac2194fbcc42edd6aa9af',
  //   messagingSenderId: '29403172094',
  //   projectId: 'commuteconnect-791a5',
  //   databaseURL: 'https://commuteconnect-791a5-default-rtdb.firebaseio.com',
  //   storageBucket: 'commuteconnect-791a5.appspot.com',
  //   iosClientId: '29403172094-ailnalfvg49ftr38rgahv6pjp4p2d8a2.apps.googleusercontent.com',
  //   iosBundleId: 'com.egoncastle.users',
  // );
}
